import Image from 'next/image'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header';
import ProfileDiv from '../components/ProfileDiv';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Suyoung's profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <ProfileDiv/>
      
    </div>
  )
}
